### ISSUE TITLE
Unable to bootstrap chef.

### ISSUE THREAD

**Issue by ghost** [gjlondon/definitive_guide_to_django_deployment#24]
(env)root@8c9003a5a765:/project/django_deployment# fab bootstrap:database
--BOOTSTRAPPING database--
--INSTALLING CHEF--
[localhost] local: knife solo prepare -i /project/django_deployment/deploy/ssh/django.pem ubuntu@ec2-52-10-254-207.us-west-2.compute.amazonaws.com
WARNING: No knife configuration file found

Bootstrapping Chef...
ERROR: RuntimeError: Unable to connect to ec2-52-10-254-207.us-west-2.compute.amazonaws.com

Fatal error: local() encountered an error (return code 100) while executing 'knife solo prepare -i /project/django_deployment/deploy/ssh/django.pem ubuntu@ec2-52-10-254-207.us-west-2.compute.amazonaws.com'

Aborting.

**Comment by daljeetv** [comment]
I was able to ssh into this webserver just a few minutes before.

Then I ran: 

echo '{
"id": "config_1",
"POSTGRES_PASS": "daljeet",
"DEBUG": "False",
"DOMAIN": "net-chat.cu.cc",
"APP_NAME": "deployment_example_project",
"DATABASE_NAME": "chat_schema",
"REPO": "django_deployment_example_project",
"GITHUB_USER": "rogueleaderr",
"DATABASE_IP": "DB_IP_SLUG",
"EC2_DNS": "WEB_IP_SLUG"
}' \
| sed -e s/DB_IP_SLUG/`cat deploy/fab_hosts/database.txt`/ \
| sed -e s/WEB_IP_SLUG/`cat deploy/fab_hosts/webserver.txt`/ \
> deploy/settings.json


After which I ran:

cd chef_files
openssl rand -base64 512 > data_bag_key
cd ..
# if you aren't using my repo's .gitingore, add the key
echo "chef_files/data_bag_key" >> .gitignore

cd chef_files
knife solo data bag create config config_1 --json-file ../deploy/settings.json
cd ..


and then I ran:

fab bootstrap:database

which is leading to the error above.

**Comment by rogueleaderr** [comment]
Did you create both the webserver AND the database (as separate nodes on ec2)? Login to your AWS console and confirm they're both there and at the DNS addresses you expect.

**Comment by daljeetv** [comment]
![screen shot 2016-03-05 at 12 35 09 pm](https://cloud.githubusercontent.com/assets/14968486/13550268/c2920f76-e2ce-11e5-862d-9543c9a6c029.png)

**Comment by rogueleaderr** [comment]
Did the webserver bootstrap correctly? Can you ssh directly into the database at the DNS that's in the error? If so to both, have you tried just terminating that database node and creating a new one (via the instructions in the guide)?

**Comment by daljeetv** [comment]
The webserver bootstraps great. 
Then I can ssh in. 

### But, then I do:

echo '{
"id": "config_1",
"POSTGRES_PASS": "",
"DEBUG": "False",
"DOMAIN": "",
"APP_NAME": "deployment_example_project",
"DATABASE_NAME": "database",
"REPO": "django_deployment_example_project",
"GITHUB_USER": "rogueleaderr",
"DATABASE_IP": "DB_IP_SLUG",
"EC2_DNS": "WEB_IP_SLUG"
}' \
| sed -e s/DB_IP_SLUG/`cat deploy/fab_hosts/database.txt`/ \
| sed -e s/WEB_IP_SLUG/`cat deploy/fab_hosts/webserver.txt`/ \
> deploy/settings.json

### and 
cd chef_files
openssl rand -base64 512 > data_bag_key
cd ..
echo "chef_files/data_bag_key" >> .gitignore
cd chef_files
knife solo data bag create config config_1 --json-file ../deploy/settings.json
cd ..

### and then I try sshing in and I get: 

![screen shot 2016-03-05 at 12 40 37 pm](https://cloud.githubusercontent.com/assets/14968486/13550310/a2a3c6ae-e2cf-11e5-8584-b5bd4c3611d1.png)

**Comment by daljeetv** [comment]
### My security group:

![screen shot 2016-03-05 at 12 43 16 pm](https://cloud.githubusercontent.com/assets/14968486/13550319/e1380df8-e2cf-11e5-935e-03d0b39a57f4.png)

**Comment by rogueleaderr** [comment]
The fabric ssh command is very simple (just open the fabfile and you can see) so if that's failing then I suspect there's something going on with your local network or security group settings or something. It's been a while since I actually ran the guide myself but I've never personally seen network errors like that.

Start by getting fab:ssh webserver and fab:ssh database to work. In the process of debugging those you'll probably figure out what's going wrong. You can refer directly to the fab file to isolate the bit of code you need to diagnose.

Also check that the DNS addresses in deploy/fab_hosts/database.txt and deploy/fab_hosts/webserver.txt/ are right. 

Also, try just terminating the instances and starting over. EC2 does sometimes allocate broken instances.

**Comment by daljeetv** [comment]
Thanks so much for your help. I think I was allocated broken instances. 
It's important to make sure you can connect:
fab ssh:webserver
fab ssh:database

...before continuing. 

If not, one should recreate instances.

**Comment by daljeetv** [comment]
I also upgraded from t2.micro -> m4.large. 
The network throughput makes a big difference during setup.
